version = 1

[[annotations]]
path = "**"
precedence = "override"
SPDX-FileCopyrightText = "2024 Stoney Jackson <dr.stoney@gmail.com>"
SPDX-License-Identifier = "GFDL-1.3-or-later"


[[annotations]]
path = "readings/slides/**"
precedence = "override"
SPDX-FileCopyrightText = "2024 Tim Fossum"
SPDX-License-Identifier = "GFDL-1.3-or-later"

[[annotations]]
path = "languages/**"
precedence = "override"
SPDX-FileCopyrightText = "2024 Tim Fossum"
SPDX-License-Identifier = "GPL-3.0-or-later"
